#%RAML 1.0 ResourceType
post:
  body:
    application/json:
      example:
        <<example3>>
  responses:
    201:
      body:
        application/json:
          example:
            message:"Event updated successfully"
                
        