#%RAML 1.0 NamedExample
value:
  summary: update meeting
  decsription: You have meeting  at 5pm today
  location: REmote/location
  startdate: 2023-09-01T17:00:00+05:30
  enddate:  2023-09-01T18:00:00+05:30
  attendees: john12@gmail.com       