#%RAML 1.0 NamedExample
value:
  summary: demo
  decsription: You have  demo meeting  at 5pm today
  location: hyderabad
  startdate: 2023-09-01T17:00:00+05:30
  enddate:  2023-09-01T18:00:00+05:30
  attendees: john123@gmail.com  